#!/usr/bin/env node

// minimalistic build step:
// grab all json schemas under schemas/, feed to tv4.js from a single schemas.js file
//

var fs = require("fs");

var out = [ "// this file is auto-generated by build_schemas.js", "" ];

fs.readdirSync("schema/").forEach(function(name) {
    var schema = JSON.parse(fs.readFileSync("schema/"+name, "utf8"));
    out.push("tv4.addSchema("+JSON.stringify(name)+", "+JSON.stringify(schema)+");");
});

fs.writeFileSync("schemas.js", out.join('\n'));